services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kuzko
      POSTGRES_PASSWORD: penis
      POSTGRES_DB: messenger
    volumes:
      - ./data:/var/lib/postgresql/data